# Generated by Django 4.2.3 on 2023-09-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='titile',
            new_name='title',
        ),
    ]
